services:
  dao-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: rbcscorpion/dao-fractio:latest # Added image name
    container_name: dao-fractio
    ports:
      - '3000:3000' # Frontend
      - '7545:7545' # Ganache
      - '8545:8545' # Additional blockchain port
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - GANACHE_HOST=0.0.0.0
    networks:
      - dao-network

  dao-test:
    build:
      context: .
      dockerfile: Dockerfile
    image: rbcscorpion/dao-fractio:test # Added test image name
    container_name: dao-fractio-runner
    command: truffle test
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - dao-app
    networks:
      - dao-network

networks:
  dao-network:
    driver: bridge
